local function tableAdd(...)
	values = {...}
	outTable = {}
	pos = 1
	
	for i,inTable in ipairs(values) do
		for index,value in ipairs(inTable) do
			outTable[pos] = value
			pos = pos + 1
		end
	end
	
	return outTable
end

local function createHeader(...)
	meta = {}
	styles = {}
	
	command_list = {
		["stylesheet"] = function(stylesheet)
			table.insert(styles, {
				["<"] = "link",
				["href"] = stylesheet,
				["rel"] = "stylesheet"
			})
		end,
		
		["description"] = function(description)
			table.insert(meta, {
				["<"] = "meta",
				["name"] = "description",
				["content"] = description
			})
		end,
		
		["title"] = function(title)
			table.insert(meta, {
				["<"] = "title",
				[">"] = title
			})
		end,
		
		["author"] = function(author)
			table.insert(meta, {
				["<"] = "meta",
				["name"] = "author",
				["content"] = author
			})
		end,
		
		["icon"] = function(icon)
			table.insert(meta, {
				["<"] = "meta",
				["name"] = "author",
				["content"] = author
			})
		end,
	}
	
	for n,command in ipairs({...} or {}) do
		for operation,data in pairs(command) do
			command_list[operation](data)
		end
	end
	
	return {
		["<"] = "head",
		[">"] = tableAdd(
			{
				"<!-- I apologize for this entire file being a mess, it was generated by a poorly implemented pre-alpha lua web framework I am in the process of writing. -->",
				{
					["<"] = "meta",
					["http-equiv"] = "Content-Type",
					["content"] = "text/html; charset=UTF-8"
				},
				{
					["<"] = "meta",
					["charset"] = "utf-8",
				},
				{
					["<"] = "meta",
					["http-equiv"] = "X-UA-Compatible",
					["content"] = "IE=edge"
				},
				{
					["<"] = "meta",
					["name"] = "viewport",
					["content"] = "width=device-width, initial-scale=1"
				},
				{
					["<"] = "link",
					["rel"] = "icon",
					["href"] = "http://getbootstrap.com/favicon.ico"
				},
				{
					["<"] = "meta",
					["name"] = "author",
					["content"] = "Matieu Lagarde"
				}
			},
			meta,
			{
				"<!-- Bootstrap core CSS -->",
				{
					["<"] = "link",
					["href"] = "./assets/bootstrap/bootstrap.min.css",
					["rel"] = "stylesheet"
				},
				"<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->",
				{
					["<"] = "link",
					["href"] = "./assets/bootstrap/ie10-viewport-bug-workaround.css",
					["rel"] = "stylesheet"
				},
				{
					["<"] = "link",
					["href"] = "./assets/css/base.css",
					["rel"] = "stylesheet"
				},
			},
			styles,
			{
				"<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->",
				"<!--[if lt IE 9]>",
				'<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>',
				'<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>',
				"<![endif]-->",
			}
		)
	}
end

return createHeader
